/*******************************************************************************
 * Copyright (c) 2000, 2021 IBM Corporation and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * This is an implementation of an early-draft specification developed under the Java
 * Community Process (JCP) and is made available for testing and evaluation purposes
 * only. The code is not compatible with any specification of the JCP.
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
package org.eclipse.jdt.internal.compiler.parser;

/*An interface that contains static declarations for some basic information
 about the parser such as the number of rules in the grammar, the starting state, etc...*/
public interface ParserBasicInformation {
	// AspectJ: Tokens taken from javadef.java, generated by jikespg according to
	// https://www.eclipse.org/jdt/core/howto/generate%20parser/generateParser.html
	int
		ERROR_SYMBOL = 142,
		MAX_NAME_LENGTH = 53,
		NUM_STATES = 1383,
		NT_OFFSET = 142,
		SCOPE_UBOUND = 396,
		SCOPE_SIZE = 397,
		LA_STATE_OFFSET = 20946,
		MAX_LA = 1,
		NUM_RULES = 1116,
		NUM_TERMINALS = 142,
		NUM_NON_TERMINALS = 487,
		NUM_SYMBOLS = 629,
		START_STATE = 1694,
		EOFT_SYMBOL = 72,
		EOLT_SYMBOL = 72,
		ACCEPT_ACTION = 20945,
		ERROR_ACTION = 20946;
}
