/*******************************************************************************
 * Copyright (c) 2000, 2019 IBM Corporation and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
package org.eclipse.jdt.internal.compiler.parser;

/*An interface that contains static declarations for some basic information
 about the parser such as the number of rules in the grammar, the starting state, etc...*/
public interface ParserBasicInformation {
	// tokens taken from javadef.java, generated by jikespg according to
	// https://www.eclipse.org/jdt/core/howto/generate%20parser/generateParser.html
	int
		ERROR_SYMBOL = 142,
		MAX_NAME_LENGTH = 53,
		NUM_STATES = 1381,
		NT_OFFSET = 142,
		SCOPE_UBOUND = 396,
		SCOPE_SIZE = 397,
		LA_STATE_OFFSET = 20848,
		MAX_LA = 1,
		NUM_RULES = 1115,
		NUM_TERMINALS = 142,
		NUM_NON_TERMINALS = 487,
		NUM_SYMBOLS = 629,
		START_STATE = 1165,
		EOFT_SYMBOL = 73,
		EOLT_SYMBOL = 73,
		ACCEPT_ACTION = 20847,
		ERROR_ACTION = 20848;
}
